# Auto-generated by .github/workflows/update-homebrew-cask.yml — do not edit by hand.
cask "sito-wireguard-vpn" do
  arch arm: "aarch64", intel: "x64"

  version "0.2.0"
  sha256 arm:   "cdb62e908144902a4c31f01020d5b7cf35d72037887777a79b0fb780c852b47c",
         intel: "4f0fa7d694672001dcb5e75c962616257f82ad88db4b2b1ead6e3bcdbbd18941"

  url "https://github.com/sito8943/sito-wireguard-vpn/releases/download/v#{version}/Sito.WireGuard.VPN_#{version}_#{arch}.dmg"
  name "Sito WireGuard VPN"
  desc "Plug-and-play WireGuard client for macOS"
  homepage "https://github.com/sito8943/sito-wireguard-vpn"

  depends_on macos: :sonoma
  depends_on formula: "wireguard-tools"

  app "Sito WireGuard VPN.app"

  zap trash: [
    "~/Library/Application Support/com.sito8943.wireguard-vpn",
    "~/Library/Caches/com.sito8943.wireguard-vpn",
  ]

  caveats <<~CAVEATS
    La app no está firmada. Quita la cuarentena tras instalar para que macOS
    no bloquee el primer arranque:
      xattr -dr com.apple.quarantine "/Applications/Sito WireGuard VPN.app"
    (o ábrela una vez con click derecho → Abrir)
  CAVEATS
end
