# Auto-generated by .github/workflows/update-homebrew-cask.yml — do not edit by hand.
cask "sito-file-browser" do
  arch arm: "aarch64", intel: "x64"

  version "0.12.0"
  sha256 arm:   "9092e5a9cfb546457a0f07bda2c31e0176c5f1cbeeed07520cac21670c758408",
         intel: "3a91d218edf7801fb0188f4b10f4ea43325bba0cb0928c427d929f3207ce63eb"

  url "https://github.com/sito8943/sito-file-browser/releases/download/v#{version}/Sito.File.Browser_#{version}_#{arch}.dmg"
  name "Sito File Browser"
  desc "File browser with an AI-friendly `sfb` CLI"
  homepage "https://github.com/sito8943/sito-file-browser"

  depends_on macos: :sonoma

  app "Sito File Browser.app"
  binary "#{appdir}/Sito File Browser.app/Contents/MacOS/sfb", target: "sfb"

  zap trash: [
    "~/Library/Application Support/com.sito8943.file-browser",
    "~/Library/Caches/com.sito8943.file-browser",
  ]
end
