# Auto-generated by .github/workflows/update-homebrew-cask.yml — do not edit by hand.
cask "sito-wireguard-vpn" do
  arch arm: "aarch64", intel: "x64"

  version "0.3.0"
  sha256 arm:   "b54c2b03695362c50e75e4cd2ba49bdab1a687f5db172aaf576e4c1a6bce4930",
         intel: "9b8e536ffac4e06318ceaf0914a2579fd6d0d25c955e8717d255ad17baa8495b"

  url "https://github.com/sito8943/sito-wireguard-vpn/releases/download/v#{version}/Sito.WireGuard.VPN_#{version}_#{arch}.dmg"
  name "Sito WireGuard VPN"
  desc "Plug-and-play WireGuard client for macOS"
  homepage "https://github.com/sito8943/sito-wireguard-vpn"

  depends_on macos: :sonoma
  depends_on formula: "wireguard-tools"

  app "Sito WireGuard VPN.app"

  zap trash: [
    "~/Library/Application Support/com.sito8943.wireguard-vpn",
    "~/Library/Caches/com.sito8943.wireguard-vpn",
  ]

  caveats <<~CAVEATS
    La app no está firmada. Quita la cuarentena tras instalar para que macOS
    no bloquee el primer arranque:
      xattr -dr com.apple.quarantine "/Applications/Sito WireGuard VPN.app"
    (o ábrela una vez con click derecho → Abrir)
  CAVEATS
end
