# Auto-generated by .github/workflows/update-homebrew-cask.yml — do not edit by hand.
cask "sito-wireguard-vpn" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.0"
  sha256 arm:   "01dd2849d0e309bfe0cbd7e22a25df1f7753e258f062db0d3e67af022e6e29f3",
         intel: "f56a95abf5acb1c5ce2e4759c4be13dce5f8d64ad9c7a4bc2fdf3b7aae4ca5eb"

  url "https://github.com/sito8943/sito-wireguard-vpn/releases/download/v#{version}/Sito.WireGuard.VPN_#{version}_#{arch}.dmg"
  name "Sito WireGuard VPN"
  desc "Plug-and-play WireGuard client for macOS"
  homepage "https://github.com/sito8943/sito-wireguard-vpn"

  depends_on macos: :sonoma
  depends_on formula: "wireguard-tools"

  app "Sito WireGuard VPN.app"

  zap trash: [
    "~/Library/Application Support/com.sito8943.wireguard-vpn",
    "~/Library/Caches/com.sito8943.wireguard-vpn",
  ]

  caveats <<~CAVEATS
    La app no está firmada. Quita la cuarentena tras instalar para que macOS
    no bloquee el primer arranque:
      xattr -dr com.apple.quarantine "/Applications/Sito WireGuard VPN.app"
    (o ábrela una vez con click derecho → Abrir)
  CAVEATS
end
