# Auto-generated by .github/workflows/update-homebrew-cask.yml — do not edit by hand.
cask "sito-file-browser" do
  arch arm: "aarch64", intel: "x64"

  version "0.13.0"
  sha256 arm:   "9cfdc996954aba02425ff8a14f61fc778baa094c0becea2f9d508e45a391dd5d",
         intel: "ec435b0a9d967c06f5e92b3ff265ee83ef87961ce7e259429d434ae409604fe7"

  url "https://github.com/sito8943/sito-file-browser/releases/download/v#{version}/Sito.File.Browser_#{version}_#{arch}.dmg"
  name "Sito File Browser"
  desc "File browser with an AI-friendly `sfb` CLI"
  homepage "https://github.com/sito8943/sito-file-browser"

  depends_on macos: :sonoma

  app "Sito File Browser.app"
  binary "#{appdir}/Sito File Browser.app/Contents/MacOS/sfb", target: "sfb"

  zap trash: [
    "~/Library/Application Support/com.sito8943.file-browser",
    "~/Library/Caches/com.sito8943.file-browser",
  ]
end
