# Auto-generated by .github/workflows/update-homebrew-cask.yml — do not edit by hand.
cask "sito-file-browser" do
  arch arm: "aarch64", intel: "x64"

  version "0.11.0"
  sha256 arm:   "3af5ab480752254ca3016e638f9d256f33ca11b5a0b49bd5d14665fc1576f8c6",
         intel: "90ae509319cb2e22280db719cb64628545b6e923a3319c9dc4738c05d193eadb"

  url "https://github.com/sito8943/sito-file-browser/releases/download/v#{version}/Sito.File.Browser_#{version}_#{arch}.dmg"
  name "Sito File Browser"
  desc "File browser with an AI-friendly `sfb` CLI"
  homepage "https://github.com/sito8943/sito-file-browser"

  depends_on macos: :sonoma

  app "Sito File Browser.app"
  binary "#{appdir}/Sito File Browser.app/Contents/MacOS/sfb", target: "sfb"

  zap trash: [
    "~/Library/Application Support/com.sito8943.file-browser",
    "~/Library/Caches/com.sito8943.file-browser",
  ]
end
